name: Submit Application

on:
  workflow_dispatch:
    inputs:
      url:
        description: "The application submission URL"
        required: true
      name:
        description: "First name"
        required: true
      email:
        description: "Your email"
        required: true
      resume_link:
        description: "Your resume link"
        required: true
      submit_application:
        description: "A flag to manually control whether pipeline submits the application or not"
        required: true
        type: boolean
        default: false
      debug:
        description: "A flag to turn on debug logging in the script"
        required: true
        type: boolean
        default: false

jobs:
  submit:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/srele96/sk-b12-env:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Cache UV
        uses: actions/cache@v5
        with:
          path: .uv-cache
          key: ${{ runner.os }}-uv-${{ hashFiles('**/uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Run Sumission Script
        env:
          # The docker container does not see the /root on the host machine and
          # we can't store cache there. That was my previous attempt at caching
          # dependencies.
          UV_CACHE_DIR: .uv-cache

          DATA_URL: ${{ github.event.inputs.url }}
          DATA_NAME: ${{ github.event.inputs.name }}
          DATA_EMAIL: ${{ github.event.inputs.email }}
          DATA_RESUME_LINK: ${{ github.event.inputs.resume_link }}
          SUBMIT_APPLICATION: ${{ github.event.inputs.submit_application }}

          DEBUG: ${{ github.event.inputs.debug }}

          DATA_REPOSITORY_LINK: "https://github.com/${{ github.repository }}"
          DATA_ACTION_RUN_LINK: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

          # Avoid storing secret in plain text
          DATA_SHA_HMAC_SECRET: ${{ secrets.DATA_SHA_HMAC_SECRET }}
        run: |
          uv sync
          uv run main.py
