name: Submit Application

on:
  workflow_dispatch:
    inputs:
      url:
        description: "The application submission URL"
        required: true
      name:
        description: "First name"
        required: true
      email:
        description: "Your email"
        required: true
      resume_link:
        description: "Your resume link"
        required: true
      submit_application:
        description: "A flag to manually control whether pipeline submits the application or not"
        required: true
        type: boolean
        default: false
      debug:
        description: "A flag to turn on debug logging in the script"
        required: true
        type: boolean
        default: false

jobs:
  submit:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/srele96/sk-b12-env:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Sumission Script
        env:
          DATA_URL: ${{ github.event.inputs.url }}
          DATA_NAME: ${{ github.event.inputs.name }}
          DATA_EMAIL: ${{ github.event.inputs.email }}
          DATA_RESUME_LINK: ${{ github.event.inputs.resume_link }}
          SUBMIT_APPLICATION: ${{ github.event.inputs.submit_application }}

          DATA_REPOSITORY_LINK: "https://github.com/${{ github.repository }}"
          DATA_ACTION_RUN_LINK: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

          # Avoid storing secret in plain text
          DATA_SHA_HMAC_SECRET: ${{ secrets.DATA_SHA_HMAC_SECRET }}
        run: |
          uv sync
          uv run main.py
